from src.metrics.information_extraction.triplet_set_f1 import TSF1
from src.metrics.information_extraction.triplet_set_precision import TSPrecision
from src.metrics.information_extraction.triplet_set_recall import TSRecall
